### ISSUE TITLE
how to get data on incoming transactions?

### ISSUE THREAD

**Issue by JonPlayGo** [St0rm1k/payeer_api#2]

**Comment by mr-st0rm** [comment]
can u find fields u need?

**Comment by JonPlayGo** [comment]
I was looking for how to get real-time data from incoming transactions

**Comment by mr-st0rm** [comment]
i think u need to/from fields
date when started and closed transaction

**Comment by mr-st0rm** [comment]
or i can't understand u

**Comment by JonPlayGo** [comment]
yes I will use this but how to output incoming transactions as soon as they arrive ? e.g. a transaction arrives and I enable a loop and if a transaction arrives it is assigned to a variable.

**Comment by mr-st0rm** [comment]
i got u
it's called a webhook

unfortunately, at the time of writing, there was probably no such thing
so, u can write something like a while loop

**Comment by JonPlayGo** [comment]
Use the "transactions_history" function in the "while" loop and check in "while" if there are new transactions?

**Comment by mr-st0rm** [comment]
yes, save transactions id that u checked, and do something with unchecked

**Comment by JonPlayGo** [comment]
thanks for your help)
